version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: polimatricula
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql:/var/lib/sql
    ports:
      - "3307:3306"
